# Generated by Django 3.2 on 2021-05-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureuser',
            name='pictures',
            field=models.ImageField(upload_to=''),
        ),
    ]
