# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpictures', '0002_alter_pictureuser_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureuser',
            name='pictures',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
