# Generated by Django 3.2 on 2021-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postsmodels_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodels',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
